site_name: Minutes
site_url: https://github.com/gabor-boros/minutes
site_description: Sync worklogs between multiple time trackers, invoicing, and bookkeeping software.
copyright: Made with ❤️ by Minutes contributors.
repo_name: gabor-boros/minutes
repo_url: https://github.com/gabor-boros/minutes
edit_uri: edit/main/www/docs/

theme:
  name: material
  language: en
  include_search_page: false
  search_index_only: true
  features:
    - navigation.tracking
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)"  # Light mode
      scheme: default
      primary: light blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"  # Dark mode
      scheme: slate
      primary: light blue
      accent: blue
      toggle:
        icon: material/toggle-switch-outline
        name: Switch to dark mode

plugins:
  - minify:
      minify_html: true
  - search:
      lang:
        - en

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/gabor-boros/minutes

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true

extra_css:
  - assets/css/minutes.css

nav:
- Introduction: index.md
- getting-started.md
- configuration.md
- Sources:
  - Clockify: sources/clockify.md
  - Tempo: sources/tempo.md
  - Timewarrior: sources/timewarrior.md
  - Toggl Track: sources/toggl.md
- Targets:
  - targets/tempo.md
- Migrations:
  - From "Tempoit": migrations/tempoit.md
  - From "Toggl to Jira": migrations/toggl-tempo-worklog-transfer.md
- Contributing: CONTRIBUTING.md
- Changelog: CHANGELOG.md
- License: LICENSE.md
