name: Build

'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        go:
          - '^1.20'
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: '${{ matrix.os }}'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '${{ matrix.go }}'
      - name: Prerequisites
        run: make prerequisites
      - name: Lint
        run: make lint
      - name: Test
        run: make test
      - name: Stash test results
        uses: actions/upload-artifact@master
        with:
          name: "Test results"
          path: .coverage.out
          retention-days: 7
      - name: Build
        run: make build

  coverage:
    name: coverage
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v3
      - name: Unstash test results
        uses: actions/download-artifact@master
        with:
          name: "Test results"
      - name: Upload test results
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: 20a724e6a2bf80ab3a3cb88c02df2e95bf918da42e63bc5eaa6f0c9dfbe7e77d
        with:
          prefix: github.com/${{github.repository}}
          coverageLocations: ${{github.workspace}}/.coverage.out:gocov
