name: Docs

'on':
  push:
    branches:
      - main
    paths:
      - www/*
  pull_request: { }

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install -r www/requirements.txt
      - run: cd www && mkdocs gh-deploy --force
